name: 'credit_propensity'
version: '1.0.0'
config-version: 2

profile: 'credit_propensity'

model-paths: ["models"]
test-paths:  ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  credit_propensity:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    features:
      +materialized: table
    mart:
      +materialized: table
